services:
  # client:
  #   container_name: quizzical_client
  #   image: node:12.18.4
  #   ports: 
  #     - 8080:8080
  #   working_dir: /code
  #   volumes:
  #     - type: bind
  #       source: ./client
  #       target: /code
  #   command: bash -c "npm install && npm run dev"
  api:
    container_name: quizzical_api
    ports: 
      - 3000:3000
    environment: 
      - PGUSER=quizzical
      - PGHOST=db
      - PGPASSWORD=password
      - PGDATABASE=quizzicalDB
      - PGPORT=5432
      - NODE_ENV=development
    depends_on:
      - db
    command: bash -c "npm install && npm run seedDev && npm run dev"

  db:
    container_name: quizzical_db
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    environment: 
      - POSTGRES_DB=quizzicalDB
      - POSTGRES_USER=quizzical
      - POSTGRES_PASSWORD=password
volumes:
  dbdata:
