services:
  api:
    container_name: quizzical_api
    ports: 
      - 3000:3000
    environment: 
      - DB_NAME=quizzical_db
      - DB_CONNECTION=mongodb://quizzicalTeam:quizzical1234@db:27017
      - NODE_ENV=development
    depends_on:
      - db
    command: bash -c "npm install && npm run dev"

  db:
    container_name: quizzical_db
    volumes:
      - "dbdata:/var/lib/mongodb/data"
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=quizzicalTeam
      - MONGO_INITDB_DATABASE=quizzical_db
      - MONGO_INITDB_ROOT_PASSWORD=quizzical1234
volumes:
  dbdata:
